#!/usr/bin/with-contenv bash

cd /opt/mstream || exit

if [ "$USE_JSON" == "true" ]; then
    exec \
        s6-setuidgid abc mstream -j /config/config.json
else
    exec \
        s6-setuidgid abc mstream -m /music -I /config/album-art/ -d /config/db/ -u ${USER} -x ${PASSWORD}
fi