#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PORT=$(jq -r '.port' /config/config.json)

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT}" \
        cd /app/mstream s6-setuidgid abc mstream -j /config/config.json
