#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/{album-art,db}

# copy config.json if doesn't exist
[[ ! -e /config/config.json ]] && \
    cp /defaults/config.json /config/config.json

# permissions
chown abc:abc -R \
    /config 
    